### ISSUE TITLE
Cell type concensus similarity matrix plot

### ISSUE THREAD

**Issue by levinhein** [zhiyhu/CIDER#3]
Hello. In this vignette, the asCIDER visualization of similarity heatmap was done for celltype_human vs. celltype_mouse:

https://zhiyhu.github.io/CIDER/articles/asCIDER.html

May I ask how can I use this without the grouping (human vs mouse). I would like to generate a consensus similarity matrix of celltype vs. celltype, if possible to be used here?

Thank you!

**Comment by zhiyhu** [comment]
Hi,

Yes that is feasible. You can use the following code from this tutorial (https://zhiyhu.github.io/CIDER/articles/dnCIDER.html)

```
dist_coef <- getDistMat(seu_list, downsampling.size = 50)
par(mfrow = c(length(seu_list),1))
for(i in which(sapply(dist_coef, function(x) return(!is.null(x))))){
  tmp <- dist_coef[[i]] + t(dist_coef[[i]])
  diag(tmp) <- 1
  pheatmap::pheatmap(tmp, display_numbers = TRUE)
}
```
